### ISSUE TITLE
Gestionar mejor los errores y agregar más contexto a los mismos

### ISSUE THREAD

**Issue by JeffreyArt1** [ogticrd/cuenta-unica-registry#102]
### Frontend
- Definir un mecanismo de manejo de errores común y compatible con i18n

### Backend
- Podría agregarse info como el User-Agent
- Mejorar la transparencia de comunicación entre el *backend del frontend* (`app/api`) y las APIs

### update `12-10-23`
- The ground work for this enhancement has been pushed at [cuenta-unica-registry/feature/i18n](https://github.com/opticrd/cuenta-unica-registry/tree/feature/i18n)

**Comment by marluanespiritusanto** [comment]
¿cómo vamos con esto? @JeffreyArt1

**Comment by JeffreyArt1** [comment]
Esto es lo que sigue después de la internacionalización, que está a tiro de hit.

**Comment by JeffreyArt1** [comment]
Changes that serves as foundation are made now in [cuenta-unica-registry/feature/new-i18n](https://github.com/opticrd/cuenta-unica-registry/tree/feature/new-i18n)

**Comment by JeffreyArt1** [comment]
Sobre este punto:
> * Mejorar la transparencia de comunicación entre el _backend del frontend_ (`app/api`) y las APIs

@marluanespiritusanto convirtió la mayoría de las llamadas hacia `app/api` en server actions en 0f8fda9ffc699963b0a9d1f80c3d42290f8bda60
