### ISSUE TITLE
Agregar gestión de internacionalización (i18N)

### ISSUE THREAD

**Issue by JeffreyArt1** [ogticrd/cuenta-unica-registry#103]
### referencias
- [Internationalization (i18n) Routing](https://nextjs.org/docs/pages/building-your-application/routing/internationalization)
- [Rosetta](https://www.npmjs.com/package/rosetta)

**Comment by JeffreyArt1** [comment]
Added initial implementation at [feature/i18n](https://github.com/opticrd/cuenta-unica-registry/tree/feature/i18n) branch

**Comment by JeffreyArt1** [comment]
Documentation of the usage can be found here: https://github.com/opticrd/cuenta-unica-registry/pull/111#issuecomment-1771045287

**Comment by gustavovalverde** [comment]
Fixed by #111
