### ISSUE TITLE
Cambiar la pantalla de confirmación de registro

### ISSUE THREAD

**Issue by gustavovalverde** [ogticrd/cuenta-unica-registry#108]
Cambiar la pantalla después del registro indicando que el correo ya ha sido enviado y que debe verificar su correo con el link recibido, según lo diseñado en Figma: https://www.figma.com/proto/obqYYdZQdcm1JNJ1XzpT0l/Cuenta-Única-Ciudadana?page-id=0%3A1&type=design&node-id=3046-45451&viewport=1051%2C2494%2C0.11&t=VsiMe2Lq1Mg5lWP5-1&scaling=min-zoom&starting-point-node-id=3046%3A45451&show-proto-sidebar=1&mode=design

**Comment by marluanespiritusanto** [comment]
Integrated
