### ISSUE TITLE
Redirect traffic to correct dashboard page or add 404 page

### ISSUE THREAD

**Issue by EnzoVezzaro** [ogticrd/cuenta-unica-registry#118]
This can be changed for a 404 page or a simple redirect to the correct dashboard page since this is user facing interface. These are just 2 examples I found browsing. I'm sure this can be improve easily 👍🏽

<img width="863" alt="Screenshot 2023-10-27 at 11 50 51" src="https://github.com/ogticrd/cuenta-unica-registry/assets/13741335/12930eea-37c3-47d0-94ee-673550379ef0">
<img width="926" alt="Screenshot 2023-10-27 at 11 50 37" src="https://github.com/ogticrd/cuenta-unica-registry/assets/13741335/c432c840-f1a3-48aa-b5f7-07ca0a4f0ef2">

**Comment by gustavovalverde** [comment]
Thank you for reporting this @EnzoVezzaro. This is an upstream issue with Ory and they're now aware of it https://github.com/ory/network/issues/355. We'll keep this open for tracking purposes until an alternative is available.

In the meanwhile, did any existing link sent you to these pages, or was it while manually changing the URL in the browser?

**Comment by EnzoVezzaro** [comment]
> In the meanwhile, did any existing link sent you to these pages, or was it while manually changing the URL in the browser?

I just remove some parts of the url manually 👍🏽
