### ISSUE TITLE
Crear las API Mockups para subir el proyecto en localhost y aportar al mismo

### ISSUE THREAD

**Issue by marluanespiritusanto** [ogticrd/cuenta-unica-registry#178]
**1. Identificar los Servicios Externos:** realizar una lista de todos los servicios externos a los que el proyecto actualmente depende, como Rekognition, la API de ciudadanos, la API de registro y Recaptcha.

**2. Crear Mock APIs:** Desarrollar mock APIs para replicar el comportamiento de los servicios externos. Estas mock APIs deberían proporcionar respuestas simuladas basadas en el comportamiento real de los servicios, pero sin interactuar con los sistemas externos. Podemos usar herramientas como JSON Server, MirageJS o simplemente crear rutas de manejo de solicitudes en tu servidor Next.js para esto.

**Comment by plusiv** [comment]
Hola Marluan, que tal esta: https://mockoon.com/

**Comment by marluanespiritusanto** [comment]
Hola @plusiv, agradecemos tu interés en contribuir a este issue.

La verdad es que Mocknoon es una opción valiosa. Sin embargo, el desafío principal radica en la capacidad de simular el comportamiento desde el mismo servidor de Next.js, evitando así el condicionamiento del código final respecto a qué API se está llamando. Esto debería permitir que cualquier persona que quiera colaborar con el proyecto a través de codespaces o devcontainers pueda hacerlo sin depender de las APIs originales o servicios externos (mocks apis).

Actualmente, el equipo está explorando alternativas para abordar esta necesidad. Sin embargo, cualquier ayuda es bienvenida.

**Comment by plusiv** [comment]
Entendido. Suena mejor en realidad!

**Comment by marluanespiritusanto** [comment]
Aún pendiente.

Retomar al migrar a Next.js 14.
