### ISSUE TITLE
Obtener código de verificación automaticamente

### ISSUE THREAD

**Issue by marluanespiritusanto** [ogticrd/cuenta-unica-registry#209]
**Objetivo**: obtener código de verificación de cuenta automáticamente desde la ruta de `/verification`.

**Descripción**: cuando un usuario recibe su correo electrónico de verificación de cuenta, se debe obtener dicho código automáticamente y colocarlo en los inputs correspondientes.

**Comment by JE1999** [comment]
el código en la ruta de `/verification` no está llegando en la URL, lo que dificulta cumplir con esta tarea.

**Comment by marluanespiritusanto** [comment]
Se retomará al implementar las nuevas vistas del IAM.
