### ISSUE TITLE
Adjust the project to be able to collaborate with the development

### ISSUE THREAD

**Issue by Devrax** [ogticrd/cuenta-unica-registry#79]
**First of all**, thanks for exposing this awesome project to the open source community.

Being honest I would like to collaborate with this project but certain APIs turn that task into a nightmare, so, I forked this project and saw that some envs like *"CEDULA_API", "JCE_PHOTO_API", "ORY_SDK_URL"* can be mocked just creating an external server that would act like an external development server for those that are not part of the core team but would like to collaborate.

Already speaking of the other dependencies to which the project obeys as **AWS** and **ORY**, I think that you must provide an step by step for any developer interested in collaborating should look for their own credentials ( Not recommended 😅) or explain some ways to mock them up.

If this issue stays open during a long time, maybe I will create that solution for the community, I am just open this issue for anyone interested as I don't have the time right now to focus on that task, I just open the invitation. :)

On tune!

**Comment by EnzoVezzaro** [comment]
Totally agree with @Devrax 👍🏽

**Comment by EnzoVezzaro** [comment]
do we have any update for this? @gustavovalverde
